networks:
  local:
    driver: "bridge"

services:
  httpbin:
    image: mccutchen/go-httpbin
    environment:
      - HTTPS_CERT_FILE=/cert/server.crt
      - HTTPS_KEY_FILE=/cert/server.key
    volumes:
      - ./cert:/cert
    networks:
      - local

  native:
    build: .
    environment:
      FETCH_MODULE_NAME: native
    networks:
      - local
    ports:
      - $PORT:3000
  undici:
    build: .
    environment:
      FETCH_MODULE_NAME: undici
    networks:
      - local
    ports:
      - $PORT:3000
  whatwg-node:
    build: .
    environment:
      FETCH_MODULE_NAME: "@whatwg-node/fetch"
    networks:
      - local
    ports:
      - $PORT:3000
  node-fetch:
    build: .
    environment:
      FETCH_MODULE_NAME: node-fetch
    networks:
      - local
    ports:
      - $PORT:3000
