name: CI
on:
  workflow_dispatch:
    inputs:
      memory:
        required: true
        description: '--max-old-space-size'
      vus:
        required: true
        description: '--vus'

jobs:
  test:
    runs-on: ubuntu-latest
    name: "Load test --vus=${{ github.event.inputs.vus }} --max-old-space-size=${{ github.event.inputs.memory }}"
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-node@v3
        with:
          node-version: 20.2.0
      
      - run: npm ci

      - name: Setup K6
        run: |
          sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys C5AD17C747E3415A3642D57D77C6C491D6AC1D69
          echo "deb https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
          sudo apt-get update
          sudo apt-get install k6=0.37.0


      - name: Run httpbin
        run: |
          docker run --rm -p "58080:8080" mccutchen/go-httpbin &
          npx wait-on http-get://localhost:58080/status/200

      - name: Run server
        run: |
          node --max-old-space-size=${{ github.event.inputs.memory }} index.js &
          npx wait-on http-get://localhost:3000

      - name: Load test
        run:
          k6 -e ENDPOINT_HOSTNAME="[::1]" run k6.js --vus=${{ github.event.inputs.vus }} --duration=3h
    
    